# Generated by Django 5.2 on 2025-07-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contact_first_alter_contact_last'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last',
        ),
    ]
